### ISSUE TITLE
Wish: support for more complex retention rules

### ISSUE THREAD

**Issue by markstos** [szkkentaro/rotate-snapshot#3]
Thanks for creating this Node.js Lambda function for expirating snapshots in AWS. I was looking for something just like this. 

It would be nice if the more flexible expiration rules from [ec2-expire-snapshots](https://github.com/alestic/ec2-expire-snapshots) could be ported here. That would allow expressing policies like this:

 * Keep 1 backup per day for the last 30 days
 * Keep 1 back per month for the last 12 months
 * Keep 1 back per year for the last 2 years

**Comment by szkkentaro** [comment]
It looks nice. I will try to add such rules.

**Comment by markstos** [comment]
The [grandfatherson](https://github.com/ecometrica/grandfatherson) library from Python implements the Grandfather Father Son rotation algorithm and is very well tested. One possibility is to port that JavaScript.

That library looks so nice, I'm considering the inverse-- porting the rest of this project to Python so I can use it. :wink:

**Comment by markstos** [comment]
I ported the `grandfatherson` project from Python to Node.js so it can be be fairly easy integrated here if someone wants to do it: https://www.npmjs.com/package/grandfatherson

**Comment by markstos** [comment]
I used grandfatherson to build my own Node.js and Lambda-based snapshot rotation tool:
https://github.com/RideAmigosCorp/lambda-expire-snapshots
